<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Carbon\Carbon;

class ComprehensiveUsersSeeder extends Seeder
{
    public function run(): void
    {
        // Create Admin Users
        $adminUsers = [
            [
                'name' => 'Διαχειριστής Κύριος',
                'email' => 'kyrios.admin@sweat24.com',
                'password' => bcrypt('password'),
                'phone' => '2101234567',
                'role' => 'admin',
                'membership_type' => 'Admin',
                'join_date' => Carbon::now()->subYears(2),
                'status' => 'active',
                'total_sessions' => 0,
                'remaining_sessions' => 0,
                'medical_history' => null,
                'last_visit' => Carbon::now()->subDays(1),
            ],
            [
                'name' => 'Μαρία Διαχειρίστρια',
                'email' => 'maria.admin@sweat24.com',
                'password' => bcrypt('password'),
                'phone' => '2101234568',
                'role' => 'admin',
                'membership_type' => 'Admin',
                'join_date' => Carbon::now()->subYear(),
                'status' => 'active',
                'total_sessions' => 0,
                'remaining_sessions' => 0,
                'medical_history' => null,
                'last_visit' => Carbon::now()->subDays(2),
            ],
        ];

        // Create Trainer Users
        $trainerUsers = [
            [
                'name' => 'Άλεξ Ροδρίγκεζ',
                'email' => 'alex@sweat24.com',
                'password' => bcrypt('password'),
                'phone' => '6944111222',
                'role' => 'trainer',
                'membership_type' => 'Trainer',
                'join_date' => Carbon::now()->subYears(3),
                'status' => 'active',
                'total_sessions' => 0,
                'remaining_sessions' => 0,
                'medical_history' => null,
                'last_visit' => Carbon::now(),
            ],
            [
                'name' => 'Εμιλι Τσεν',
                'email' => 'emily@sweat24.com',
                'password' => bcrypt('password'),
                'phone' => '6955222333',
                'role' => 'trainer',
                'membership_type' => 'Trainer',
                'join_date' => Carbon::now()->subYears(2),
                'status' => 'active',
                'total_sessions' => 0,
                'remaining_sessions' => 0,
                'medical_history' => null,
                'last_visit' => Carbon::now(),
            ],
            [
                'name' => 'Τζέιμς Τέιλορ',
                'email' => 'james@sweat24.com',
                'password' => bcrypt('password'),
                'phone' => '6966333444',
                'role' => 'trainer',
                'membership_type' => 'Trainer',
                'join_date' => Carbon::now()->subYears(4),
                'status' => 'active',
                'total_sessions' => 0,
                'remaining_sessions' => 0,
                'medical_history' => null,
                'last_visit' => Carbon::now(),
            ],
            [
                'name' => 'Σάρα Τζόνσον',
                'email' => 'sarah@sweat24.com',
                'password' => bcrypt('password'),
                'phone' => '6977444555',
                'role' => 'trainer',
                'membership_type' => 'Trainer',
                'join_date' => Carbon::now()->subYears(1),
                'status' => 'active',
                'total_sessions' => 0,
                'remaining_sessions' => 0,
                'medical_history' => null,
                'last_visit' => Carbon::now()->subDays(1),
            ],
        ];

        // Create Member Users with various scenarios
        $memberUsers = [
            [
                'name' => 'Γιάννης Παπαδόπουλος',
                'email' => 'giannis@email.com',
                'password' => bcrypt('password'),
                'phone' => '6944123456',
                'role' => 'member',
                'membership_type' => 'Premium',
                'join_date' => Carbon::now()->subMonths(8),
                'status' => 'active',
                'total_sessions' => 45,
                'remaining_sessions' => 8,
                'medical_history' => 'Χωρίς ιδιαίτερες παθήσεις',
                'last_visit' => Carbon::now()->subDays(3),
            ],
            [
                'name' => 'Μαρία Κωνσταντίνου',
                'email' => 'maria@email.com',
                'password' => bcrypt('password'),
                'phone' => '6955234567',
                'role' => 'member',
                'membership_type' => 'Basic',
                'join_date' => Carbon::now()->subMonths(6),
                'status' => 'active',
                'total_sessions' => 28,
                'remaining_sessions' => 3,
                'medical_history' => 'Πρόβλημα στη μέση - αποφυγή βαρέων βαρών',
                'last_visit' => Carbon::now()->subDays(2),
            ],
            [
                'name' => 'Κώστας Δημητρίου',
                'email' => 'kostas@email.com',
                'password' => bcrypt('password'),
                'phone' => '6966345678',
                'role' => 'member',
                'membership_type' => 'Premium',
                'join_date' => Carbon::now()->subMonths(10),
                'status' => 'expired',
                'total_sessions' => 52,
                'remaining_sessions' => 0,
                'medical_history' => 'Αθλητικός τραυματισμός γόνατος - φυσιοθεραπεία',
                'last_visit' => Carbon::now()->subDays(15),
            ],
            [
                'name' => 'Άννα Μιχαήλ',
                'email' => 'anna@email.com',
                'password' => bcrypt('password'),
                'phone' => '6977123789',
                'role' => 'member',
                'membership_type' => 'Basic',
                'join_date' => Carbon::now()->subMonths(3),
                'status' => 'active',
                'total_sessions' => 15,
                'remaining_sessions' => 12,
                'medical_history' => 'Χωρίς ιδιαίτερες παθήσεις',
                'last_visit' => Carbon::now()->subDays(1),
            ],
            [
                'name' => 'Νίκος Αλεξανδρίδης',
                'email' => 'nikos@email.com',
                'password' => bcrypt('password'),
                'phone' => '6988456123',
                'role' => 'member',
                'membership_type' => 'Premium',
                'join_date' => Carbon::now()->subMonths(12),
                'status' => 'active',
                'total_sessions' => 95,
                'remaining_sessions' => 25,
                'medical_history' => 'Υπέρταση - αποφυγή έντονων καρδιαγγειακών',
                'last_visit' => Carbon::now()->subDays(4),
            ],
            [
                'name' => 'Ελένη Παπαγιάννη',
                'email' => 'eleni@email.com',
                'password' => bcrypt('password'),
                'phone' => '6999567234',
                'role' => 'member',
                'membership_type' => 'Basic',
                'join_date' => Carbon::now()->subMonths(2),
                'status' => 'active',
                'total_sessions' => 8,
                'remaining_sessions' => 7,
                'medical_history' => 'Άσθμα - φέρνει inhaler',
                'last_visit' => Carbon::now()->subDays(5),
            ],
            [
                'name' => 'Δημήτρης Κωνσταντίνου',
                'email' => 'dimitris@email.com',
                'password' => bcrypt('password'),
                'phone' => '6944678345',
                'role' => 'member',
                'membership_type' => 'Premium',
                'join_date' => Carbon::now()->subMonths(14),
                'status' => 'active',
                'total_sessions' => 120,
                'remaining_sessions' => 18,
                'medical_history' => 'Προηγούμενος τραυματισμός ώμου - αποφυγή overhead κινήσεων',
                'last_visit' => Carbon::now()->subDays(1),
            ],
            [
                'name' => 'Χριστίνα Νικολάου',
                'email' => 'christina@email.com',
                'password' => bcrypt('password'),
                'phone' => '6955789456',
                'role' => 'member',
                'membership_type' => 'Basic',
                'join_date' => Carbon::now()->subWeeks(2),
                'status' => 'active',
                'total_sessions' => 3,
                'remaining_sessions' => 2,
                'medical_history' => 'Χωρίς ιδιαίτερες παθήσεις - αρχάρια',
                'last_visit' => Carbon::now()->subDays(6),
            ],
            [
                'name' => 'Παναγιώτης Γεωργίου',
                'email' => 'panagiotis@email.com',
                'password' => bcrypt('password'),
                'phone' => '6966890567',
                'role' => 'member',
                'membership_type' => 'Premium',
                'join_date' => Carbon::now()->subMonths(7),
                'status' => 'active',
                'total_sessions' => 62,
                'remaining_sessions' => 5,
                'medical_history' => 'Διαβήτης τύπου 2 - παρακολούθηση γλυκόζης',
                'last_visit' => Carbon::now()->subDays(2),
            ],
            [
                'name' => 'Σοφία Μανουσάκη',
                'email' => 'sofia@email.com',
                'password' => bcrypt('password'),
                'phone' => '6977901678',
                'role' => 'member',
                'membership_type' => 'Basic',
                'join_date' => Carbon::now()->subMonths(5),
                'status' => 'active',
                'total_sessions' => 22,
                'remaining_sessions' => 1,
                'medical_history' => 'Χωρίς ιδιαίτερες παθήσεις',
                'last_visit' => Carbon::now()->subDays(8),
            ],
            [
                'name' => 'Αντώνης Καραμάνος',
                'email' => 'antonis@email.com',
                'password' => bcrypt('password'),
                'phone' => '6988012789',
                'role' => 'member',
                'membership_type' => 'Premium',
                'join_date' => Carbon::now()->subMonths(18),
                'status' => 'expired',
                'total_sessions' => 145,
                'remaining_sessions' => 0,
                'medical_history' => 'Προηγούμενη εγχείρηση μηνίσκου - αποφυγή deep squats',
                'last_visit' => Carbon::now()->subDays(25),
            ],
            [
                'name' => 'Βασιλική Τσιάπα',
                'email' => 'vasiliki@email.com',
                'password' => bcrypt('password'),
                'phone' => '6999123890',
                'role' => 'member',
                'membership_type' => 'Basic',
                'join_date' => Carbon::now()->subDays(10),
                'status' => 'active',
                'total_sessions' => 1,
                'remaining_sessions' => 0,
                'medical_history' => 'Εγκυμοσύνη - προγεννητικός fitness',
                'last_visit' => Carbon::now()->subDays(10),
            ],
            [
                'name' => 'Γιώργος Στεφανίδης',
                'email' => 'giorgos@email.com',
                'password' => bcrypt('password'),
                'phone' => '6944234901',
                'role' => 'member',
                'membership_type' => 'Premium',
                'join_date' => Carbon::now()->subMonths(9),
                'status' => 'active',
                'total_sessions' => 78,
                'remaining_sessions' => 22,
                'medical_history' => 'Χωρίς ιδιαίτερες παθήσεις - προχωρημένος αθλητής',
                'last_visit' => Carbon::now(),
            ],
            [
                'name' => 'Ιωάννα Λαμπρου',
                'email' => 'ioanna@email.com',
                'password' => bcrypt('password'),
                'phone' => '6955345012',
                'role' => 'member',
                'membership_type' => 'Basic',
                'join_date' => Carbon::now()->subMonths(4),
                'status' => 'active',
                'total_sessions' => 18,
                'remaining_sessions' => 9,
                'medical_history' => 'Σκολίωση - ειδικές ασκήσεις για τη στάση',
                'last_visit' => Carbon::now()->subDays(3),
            ],
        ];

        // Create all users
        foreach (array_merge($adminUsers, $trainerUsers, $memberUsers) as $userData) {
            User::create($userData);
        }

        $this->command->info('Comprehensive users seeded successfully!');
        $this->command->info('- 2 Admin users created');
        $this->command->info('- 4 Trainer users created');
        $this->command->info('- 14 Member users created');
        $this->command->info('Total: 20 users with various scenarios');
    }
}